language: php

php:
  - 5.6
  - 7.0
  - 7.1

env:
  - DB=mysql db_dsn='mysql://root@127.0.0.1/cakephp_test'
  - DB=pgsql db_dsn='postgres://postgres@127.0.0.1/cakephp_test'

matrix:
  fast_finish: true
  include:
    - php: 5.6
      env:
        - COVERALLS=1
    - php: 5.6
      env:
        - PHPCS=1
    - php: 5.6
      env:
        - FOC_VALIDATE=1

install:
  - composer install --prefer-source --no-interaction

before_script:
  - if [ $COVERALLS = 1 ]; then composer require --dev satooshi/php-coveralls:dev-master; fi
  - if [ $COVERALLS = 1 ]; then mkdir -p build/logs; fi

  - if [ $DB = 'mysql' ]; then mysql -e 'CREATE DATABASE cakephp_test;'; fi
  - if [ $DB = 'pgsql' ]; then psql -c 'CREATE DATABASE cakephp_test;' -U postgres; fi

script:
  - if [[ $PHPCS != '1' ]]; then vendor/bin/phpunit; fi
  - if [ $PHPCS = 1 ]; then vendor/bin/phpcs; fi
  - if [ $COVERALLS = 1 ]; then vendor/bin/phpunit --stderr --coverage-clover build/logs/clover.xml; fi

after_script:
  - if [ $COVERALLS = 1 ]; then php vendor/bin/coveralls -c .coveralls.yml -v; fi

notifications:
  email: false
